# Generated by Django 2.2.6 on 2019-10-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20191012_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(blank=True, choices=[('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю')], max_length=1, null=True),
        ),
    ]
